username = "*[data-test=\"username\"]"
password = "*[data-test=\"password\"]"
loginButton = "*[data-test=\"login-button\"]"
appLogo = ".app_logo"
addProduct1 = "*[data-test=\"add-to-cart-sauce-labs-backpack\"]"
addProduct2 = "*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]"
shoppingCardLink = "*[data-test=\"shopping-cart-link\"]"
verifyProduct1 = "*[data-test=\"inventory-item-name\"]"
verifyProduct2 = "#item_1_title_link > .inventory_item_name"
verifyProduct1_text = "Sauce Labs Backpack"
verifyProduct2_text = "Sauce Labs Bolt T-Shirt"
checkOutError_text = "Error: First Name is required"
verifyLogo = "Swag Labs"
checkOut = "*[data-test=\"checkout\"]"
checkOutContinue = "*[data-test=\"continue\"]"
checkOutError = "*[data-test=\"error\"]"
loginError = "*[data-test=\"error\"]"
emptyUsernameloginErrorMessage = "Epic sadface: Username is required"
emptyPasswordloginErrorMessage = "Epic sadface: Password is required"
wrongUserPassloginErrorMessage = "Epic sadface: Username and password do not match any user in this service"
lockedLoginErrorMessage = "Epic sadface: Sorry, this user has been locked out."
removeProduct1 = "*[data-test=\"remove-sauce-labs-backpack\"]"
removeProduct2 = "*[data-test=\"remove-sauce-labs-bolt-t-shirt\"]"