BASE_URL = "https://www.saucedemo.com/"
username_id = "user-name"
password_id = "password"
login_button_id = "login-button"
locate_logo = "//*[@id='header_container']/div[1]/div[2]/div"
list_count_test = "inventory_item"
test_result_id = "//*[@id='header_container']/div[1]/div[2]/div"
add_to_card_xpath = "//*[@id='add-to-cart-sauce-labs-bike-light']"
checkout_xpath = "/html/body/div/div/div/div[1]/div[1]/div[3]/a"
bike_light_product = "/html/body/div/div/div/div[2]/div/div[1]/div[3]/div[2]/a/div"
bike_light_product_text = "Sauce Labs Bike Light"
checkout_button_xpath = "//*[@id='checkout']"
continue_button_xpath = "//*[@id='continue']"
remove_from_card = "//*[@id='remove-sauce-labs-bike-light']"
checkout_error_xpath = "//*[@id='checkout_info_container']/div/form/div[1]/div[4]/h3"
errorMessage_xpath = "//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage_text = "Epic sadface: Username and password do not match any user in this service"
errorMessage1_text = "Epic sadface: Sorry, this user has been locked out."
errorMessage2_text = "Epic sadface: Password is required"
errorMessage3_text = "Epic sadface: Username is required"
errorMessage4_text = "Error: First Name is required"